robot:
  wheel_radius: 5.5                    # raj 1 -> 5
  width:  16.5                         # raj 1 -> 16.5
  delta_t: 0.1 # in seconds

camera:
  y_offset: 20                         # raj 0 -> 20
  z_offset: 1                          # raj 0 -> 1
  y_angle: 17.5                        # raj 0 -> 17.5
  exposure_time: 60
  gain: 100

ekf_slam:
  robot_width: 0
  motor_std: 0
  dist_std: 0
  angle_std: 0

